backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'redirects'
    label: 'Redirects'
    format: 'json'
    folder: 'assets/content/redirects'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'From', name: 'from', widget: 'string', hint: 'For example: /eatingout' }
      - { label: 'To', name: 'to', widget: 'string', hint: 'For example: https://docs.google.com/forms/d/e/1FAIpQLScc8iucZ' }
      - { label: 'Status Code', name: 'number', valueType: 'int', hint: 'For example: 301', required: false, widget: 'number' }
